[package]
name = "ooxml"
edition.workspace = true
version.workspace = true
homepage = { workspace = true }
license = { workspace = true }

[dependencies]
ctxole = { workspace = true }
vba = { path = "../vba" }
ctxunzip = { path = "../../../libs/ctxunzip" }
convert_case = "0.8.0"
bitflags = "2.5.0"
quick-xml = { workspace = true }
serde = { workspace = true }
regex = { workspace = true }
time = { workspace = true, features = [ "parsing" ] }
tempfile = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ctxutils = { workspace = true }
utf8dec-rs = { workspace = true }
