[package]
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true
name = "endpoint"
description = "Job request API endpoint"

[dependencies]
shared = { path = "../shared" }
tokio = { workspace = true, features = [ "fs" ] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
amqprs = { workspace = true }
figment = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
futures = { workspace = true }
tokio-postgres = { workspace = true }
pgrules = { workspace = true }
actix-web = "4"
actix-multipart = "0.7"
deadpool-postgres = "0.14.1"
tokio-util = { version = "0.7.10", features = [ "io" ] }
