max_processed_size = 262144000
max_children = 100
max_child_input_size = 41943040
max_child_output_size = 41943040
max_entries_to_process = 2000
objects_path = "/var/lib/objects"
output_path = "/tmp"
