stages:
  - build
  - publish

build frontend:
  stage: build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/rust:latest
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dev.contextal.com/".insteadOf "ssh://git@gitlab.dev.contextal.com:2022/"
  script:
    - rustc --version && cargo --version
    - cargo build --verbose --release
    - cargo test --verbose --release
  artifacts:
    paths:
      - target/release/frontend

build frontend-unknown:
  stage: build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/rust:latest
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dev.contextal.com/".insteadOf "ssh://git@gitlab.dev.contextal.com:2022/"
  script:
    - rustc --version && cargo --version
    - cargo build --verbose --release --no-default-features
    - mv -f target/release/frontend target/release/frontend-unknown
  artifacts:
    paths:
      - target/release/frontend-unknown

dockerize:
  stage: publish
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:latest
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:dind
      alias: docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_TAG" =~ '^((0|([1-9][0-9]*))\.){2}(0|([1-9][0-9]*))(-((0|([1-9][0-9]*)|([0-9]*[a-zA-Z-][0-9a-zA-Z-]*))(\.(0|([1-9][0-9]*)|([0-9]*[a-zA-Z-][0-9a-zA-Z-]*)))*))?$' ]]; then
        tag=":$CI_COMMIT_TAG"
        echo "Running on a release tag: $tag"
      elif [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
