#[allow(clippy::enum_variant_names, clippy::upper_case_acronyms)]
#[derive(Debug, PartialEq)]
pub enum RecordType {
    AbsPath15,
    ACBegin,
    ACEnd,
    ActiveX,
    AFilterDateGroupItem,
    ArrFmla,
    BeginActiveXControls,
    BeginAFilter,
    BeginAutoSortScope,
    BeginBook,
    BeginBookViews,
    BeginBorders,
    BeginBundleShs,
    BeginCacheVersionInfo,
    BeginCalcFeatures,
    BeginCellIgnoreECs,
    BeginCellIgnoreECs14,
    BeginCellSmartTag,
    BeginCellSmartTags,
    BeginCellStyleXFs,
    BeginCellWatches,
    BeginCellXFs,
    BeginCFRule,
    BeginCFRule14,
    BeginColBrk,
    BeginColInfos,
    BeginColorPalette,
    BeginColorScale,
    BeginColorScale14,
    BeginComment,
    BeginCommentAuthors,
    BeginCommentList,
    BeginComments,
    BeginConditionalFormatting,
    BeginConditionalFormatting14,
    BeginConditionalFormattings,
    BeginCRErrs,
    BeginCsView,
    BeginCsViews,
    BeginCustomFilters,
    BeginCustomFilters14,
    BeginCustomRichFilters,
    BeginDatabar,
    BeginDatabar14,
    BeginDataFeedPr15,
    BeginDataModel,
    BeginDbTables15,
    BeginDCon,
    BeginDecoupledPivotCacheIDs,
    BeginDeletedName,
    BeginDeletedNames,
    BeginDim,
    BeginDims,
    BeginDRefs,
    BeginDVals,
    BeginDVals14,
    BeginDxF14s,
    BeginDXFs,
    BeginDXFs15,
    BeginDynamicArrayPr,
    BeginECDbProps,
    BeginECOlapProps,
    BeginECParam,
    BeginECParams,
    BeginECTwFldInfo,
    BeginECTwFldInfo15,
    BeginECTWFldInfoLst,
    BeginECTWFldInfoLst15,
    BeginECTxtWiz,
    BeginECTxtWiz15,
    BeginECWebProps,
    BeginEcWpTables,
    BeginEsfmd,
    BeginEsmdb,
    BeginEsmdtinfo,
    BeginEsmdx,
    BeginEsstr,
    BeginExtConn14,
    BeginExtConn15,
    BeginExtConnection,
    BeginExtConnections,
    BeginExternals,
    BeginFills,
    BeginFilterColumn,
    BeginFilters,
    BeginFmd,
    BeginFmts,
    BeginFnGroup,
    BeginFonts,
    BeginHeaderFooter,
    BeginIconSet,
    BeginIconSet14,
    BeginIndexedColors,
    BeginISXTHCols,
    BeginISXTHRws,
    BeginISXVDCols,
    BeginISXVDRws,
    BeginISXVIs,
    BeginItemUniqueNames,
    BeginList,
    BeginListCol,
    BeginListCols,
    BeginListParts,
    BeginListXmlCPr,
    BeginMap,
    BeginMdx,
    BeginMdxKPI,
    BeginMdxMbrProp,
    BeginMdxSet,
    BeginMdxTuple,
    BeginMergeCells,
    BeginMetadata,
    BeginMG,
    BeginMGMaps,
    BeginMgs,
    BeginModelRelationships,
    BeginModelTables,
    BeginModelTimeGrouping,
    BeginModelTimeGroupings,
    BeginMRUColors,
    BeginOledbPr15,
    BeginOleObjects,
    BeginPCD14,
    BeginPCDCalcItem,
    BeginPCDCalcItems,
    BeginPCDCalcMem,
    BeginPCDCalcMem14,
    BeginPCDCalcMemExt,
    BeginPCDCalcMems,
    BeginPCDCalcMemsExt,
    BeginPCDFAtbl,
    BeginPCDFGDiscrete,
    BeginPCDFGItems,
    BeginPCDFGRange,
    BeginPCDFGroup,
    BeginPCDField,
    BeginPCDFields,
    BeginPCDHFieldsUsage,
    BeginPCDHGLevel,
    BeginPCDHGLevels,
    BeginPCDHGLGMember,
    BeginPCDHGLGMembers,
    BeginPCDHGLGroup,
    BeginPCDHGLGroups,
    BeginPCDHierarchies,
    BeginPCDHierarchy,
    BeginPCDIRun,
    BeginPCDKPI,
    BeginPCDKPIs,
    BeginPCDSConsol,
    BeginPCDSCPage,
    BeginPCDSCPages,
    BeginPCDSCPItem,
    BeginPCDSCSet,
    BeginPCDSCSets,
    BeginPCDSDTCEMember,
    BeginPCDSDTCEMembers,
    BeginPCDSDTCEMembersSortBy,
    BeginPCDSDTCEntries,
    BeginPCDSDTCQueries,
    BeginPCDSDTCQuery,
    BeginPCDSDTCSet,
    BeginPCDSDTCSets,
    BeginPCDSDTupleCache,
    BeginPcdSFCIEntries,
    BeginPCDSource,
    BeginPCDSRange,
    BeginPivotCacheDef,
    BeginPivotCacheID,
    BeginPivotCacheIDs,
    BeginPivotCacheRecords,
    BeginPivotTableRefs,
    BeginPivotTableUISettings,
    BeginPivotVersionInfo,
    BeginPName,
    BeginPNames,
    BeginPNPair,
    BeginPNPairs,
    BeginPRFilter,
    BeginPRFilter14,
    BeginPRFilters,
    BeginPRFilters14,
    BeginPRFItem,
    BeginPRFItem14,
    BeginPRule,
    BeginPRule14,
    BeginQSI,
    BeginQSIF,
    BeginQSIFs,
    BeginQSIR,
    BeginRichFilterColumn,
    BeginRichFilters,
    BeginRichSortCondition,
    BeginRichValueBlock,
    BeginRRSort,
    BeginRwBrk,
    BeginScenMan,
    BeginSct,
    BeginSheet,
    BeginSheetData,
    BeginSingleCells,
    BeginSlicer,
    BeginSlicerCache,
    BeginSlicerCacheDef,
    BeginSlicerCacheID,
    BeginSlicerCacheIDs,
    BeginSlicerCacheLevelData,
    BeginSlicerCacheLevelsData,
    BeginSlicerCacheNative,
    BeginSlicerCacheOlapImpl,
    BeginSlicerCacheSelections,
    BeginSlicerCacheSiRange,
    BeginSlicerCacheSiRanges,
    BeginSlicerCachesPivotCacheID,
    BeginSlicerCachesPivotCacheIDs,
    BeginSlicerEx,
    BeginSlicers,
    BeginSlicersEx,
    BeginSlicerStyle,
    BeginSlicerStyleElements,
    BeginSlicerStyles,
    BeginSmartTags,
    BeginSmartTagTypes,
    BeginSortCond,
    BeginSortCond14,
    BeginSortState,
    BeginSparklineGroup,
    BeginSparklineGroups,
    BeginSparklines,
    BeginSst,
    BeginStyles,
    BeginStyleSheet,
    BeginStyleSheetExt14,
    BeginSupBook,
    BeginSXChange,
    BeginSXChanges,
    BeginSXCondFmt,
    BeginSXCondFmt14,
    BeginSXCondFmts,
    BeginSXCondFmts14,
    BeginSXCrtFormat,
    BeginSXCrtFormats,
    BeginSXDI,
    BeginSXDIs,
    BeginSXEdit,
    BeginSXEdits,
    BeginSXFILTER,
    BeginSXFilters,
    BeginSXFormat,
    BeginSXFormats,
    BeginSXLI,
    BeginSXLICols,
    BeginSXLIRws,
    BeginSXLocation,
    BeginSXPI,
    BeginSXPIs,
    BeginSxRow,
    BeginSxrules,
    BeginSxrules14,
    BeginSxSelect,
    BeginSXTDMP,
    BeginSXTDMPS,
    BeginSXTH,
    BeginSXTHItem,
    BeginSXTHItems,
    BeginSXTHs,
    BeginSXTupleSet,
    BeginSXTupleSetData,
    BeginSXTupleSetHeader,
    BeginSXTupleSetRow,
    BeginSxvcells,
    BeginSXVD,
    BeginSXVDs,
    BeginSXVI,
    BeginSXView,
    BeginSxView14,
    BeginSXView16,
    BeginSXVIs,
    BeginTableSlicerCache,
    BeginTableStyle,
    BeginTableStyles,
    BeginTimelineCacheID,
    BeginTimelineCacheIDs,
    BeginTimelineCachePivotCacheIDs,
    BeginTimelineEx,
    BeginTimelinesEx,
    BeginTimelineStyle,
    BeginTimelineStyleElements,
    BeginTimelineStyles,
    BeginTimelineStylesheetExt15,
    BeginUserCsView,
    BeginUserCsViews,
    BeginUsers,
    BeginUserShView,
    BeginUserShViews,
    BeginVolDeps,
    BeginVolMain,
    BeginVolTopic,
    BeginVolType,
    BeginWebExtensions,
    BeginWebPubItem,
    BeginWebPubItems,
    BeginWsSortMap,
    BeginWsView,
    BeginWsViews,
    BigName,
    BkHim,
    BookProtection,
    BookProtectionIso,
    BookView,
    Border,
    Brk,
    BundleSh,
    CalcFeature,
    CalcProp,
    CellBlank,
    CellBool,
    CellError,
    CellIgnoreEC,
    CellIgnoreEC14,
    CellIsst,
    CellMeta,
    CellReal,
    CellRk,
    CellRString,
    CellSmartTagProperty,
    CellSt,
    CellWatch,
    CFIcon,
    CFRuleExt,
    CFVO,
    CFVO14,
    ColInfo,
    Color,
    Color14,
    ColorFilter,
    CommentAuthor,
    CommentText,
    CrashRecErr,
    CsPageSetup,
    CsProp,
    CsProtection,
    CsProtectionIso,
    CUsr,
    CustomFilter,
    CustomFilter14,
    CustomRichFilter,
    DbCommand15,
    DbTable15,
    DecoupledPivotCacheID,
    Drawing,
    DRef,
    DVal,
    DVal14,
    DValList,
    DXF,
    DXF14,
    DXF15,
    DynamicFilter,
    DynamicRichFilter,
    EndActiveXControls,
    EndAFilter,
    EndAutoSortScope,
    EndBook,
    EndBookViews,
    EndBorders,
    EndBundleShs,
    EndCacheVersionInfo,
    EndCalcFeatures,
    EndCellIgnoreECs,
    EndCellIgnoreECs14,
    EndCellSmartTag,
    EndCellSmartTags,
    EndCellStyleXFs,
    EndCellWatches,
    EndCellXFs,
    EndCFRule,
    EndCFRule14,
    EndColBrk,
    EndColInfos,
    EndColorPalette,
    EndColorScale,
    EndColorScale14,
    EndComment,
    EndCommentAuthors,
    EndCommentList,
    EndComments,
    EndConditionalFormatting,
    EndConditionalFormatting14,
    EndConditionalFormattings,
    EndCRErrs,
    EndCsView,
    EndCsViews,
    EndCustomFilters,
    EndCustomRichFilters,
    EndDatabar,
    EndDatabar14,
    EndDataFeedPr15,
    EndDataModel,
    EndDbTables15,
    EndDCon,
    EndDecoupledPivotCacheIDs,
    EndDeletedName,
    EndDeletedNames,
    EndDim,
    EndDims,
    EndDRefs,
    EndDVals,
    EndDVals14,
    EndDxf14s,
    EndDXFs,
    EndDXFs15,
    EndDynamicArrayPr,
    EndECDbProps,
    EndECOlapProps,
    EndECParam,
    EndECParams,
    EndECTWFldInfoLst,
    EndECTWFldInfoLst15,
    EndECTxtWiz,
    EndECTxtWiz15,
    EndECWebProps,
    EndECWPTables,
    EndEsfmd,
    EndEsmdb,
    EndEsmdtinfo,
    EndEsmdx,
    EndEsstr,
    EndExtConn14,
    EndExtConn15,
    EndExtConnection,
    EndExtConnections,
    EndExternals,
    EndFills,
    EndFilterColumn,
    EndFilters,
    EndFmd,
    EndFmts,
    EndFnGroup,
    EndFonts,
    EndHeaderFooter,
    EndIconSet,
    EndIconSet14,
    EndIndexedColors,
    EndISXTHCols,
    EndISXTHRws,
    EndISXVDCols,
    EndISXVDRws,
    EndISXVIs,
    EndItemUniqueNames,
    EndList,
    EndListCol,
    EndListCols,
    EndListParts,
    EndListXmlCPr,
    EndMap,
    EndMdx,
    EndMdxKPI,
    EndMdxMbrProp,
    EndMdxSet,
    EndMdxTuple,
    EndMergeCells,
    EndMetadata,
    EndMG,
    EndMGMaps,
    EndMGs,
    EndModelRelationships,
    EndModelTables,
    EndModelTimeGrouping,
    EndModelTimeGroupings,
    EndMRUColors,
    EndOledbPr15,
    EndOleObjects,
    EndPCD14,
    EndPCDCalcItem,
    EndPCDCalcItems,
    EndPCDCalcMem,
    EndPCDCalcMem14,
    EndPCDCalcMemExt,
    EndPCDCalcMems,
    EndPCDCalcMemsExt,
    EndPCDFAtbl,
    EndPCDFGDiscrete,
    EndPCDFGItems,
    EndPCDFGRange,
    EndPCDFGroup,
    EndPCDField,
    EndPCDFields,
    EndPCDHFieldsUsage,
    EndPCDHGLevel,
    EndPCDHGLevels,
    EndPCDHGLGMember,
    EndPCDHGLGMembers,
    EndPCDHGLGroup,
    EndPCDHGLGroups,
    EndPCDHierarchies,
    EndPCDHierarchy,
    EndPCDIRun,
    EndPCDKPI,
    EndPCDKPIs,
    EndPCDSConsol,
    EndPCDSCPage,
    EndPCDSCPages,
    EndPCDSCPItem,
    EndPCDSCSet,
    EndPCDSCSets,
    EndPCDSDTCEMember,
    EndPCDSDTCEMembers,
    EndPCDSDTCEntries,
    EndPCDSDTCQueries,
    EndPCDSDTCQuery,
    EndPCDSDTCSet,
    EndPCDSDTCSets,
    EndPCDSDTupleCache,
    EndPCDSFCIEntries,
    EndPCDSource,
    EndPCDSRange,
    EndPivotCacheDef,
    EndPivotCacheID,
    EndPivotCacheIDs,
    EndPivotCacheRecords,
    EndPivotTableRefs,
    EndPivotTableUISettings,
    EndPivotVersionInfo,
    EndPName,
    EndPNames,
    EndPNPair,
    EndPNPairs,
    EndPRFilter,
    EndPRFilter14,
    EndPRFilters,
    EndPRFilters14,
    EndPRFItem,
    EndPRFItem14,
    EndPRule,
    EndPRule14,
    EndQSI,
    EndQSIF,
    EndQSIFs,
    EndQSIR,
    EndRichFilterColumn,
    EndRichFilters,
    EndRichSortCondition,
    EndRichValueBlock,
    EndRRSort,
    EndRwBrk,
    EndScenMan,
    EndSct,
    EndSheet,
    EndSheetData,
    EndSingleCells,
    EndSlicer,
    EndSlicerCache,
    EndSlicerCacheDef,
    EndSlicerCacheID,
    EndSlicerCacheIDs,
    EndSlicerCacheLevelData,
    EndSlicerCacheLevelsData,
    EndSlicerCacheNative,
    EndSlicerCacheOlapImpl,
    EndSlicerCacheSelections,
    EndSlicerCacheSiRange,
    EndSlicerCacheSiRanges,
    EndSlicerCachesPivotCacheID,
    EndSlicerCachesPivotCacheIDs,
    EndSlicerEx,
    EndSlicers,
    EndSlicersEx,
    EndSlicerStyle,
    EndSlicerStyleElements,
    EndSlicerStyles,
    EndSmartTags,
    EndSmartTagTypes,
    EndSortCond,
    EndSortCond14,
    EndSortState,
    EndSparklineGroup,
    EndSparklineGroups,
    EndSparklines,
    EndSst,
    EndStyles,
    EndStyleSheet,
    EndStyleSheetExt14,
    EndSupBook,
    EndSXChange,
    EndSXChanges,
    EndSXCondFmt,
    EndSXCondFmt14,
    EndSXCondFmts,
    EndSXCondFmts14,
    EndSXCrtFormat,
    EndSXCrtFormats,
    EndSXDI,
    EndSXDIs,
    EndSXEdit,
    EndSXEdits,
    EndSXFilter,
    EndSXFilters,
    EndSXFormat,
    EndSxFormats,
    EndSXLI,
    EndSXLICols,
    EndSXLIRws,
    EndSXLocation,
    EndSXPI,
    EndSXPIs,
    EndSxRow,
    EndSxRules,
    EndSxrules14,
    EndSxSelect,
    EndSXTDMP,
    EndSXTDMPs,
    EndSXTH,
    EndSXTHItem,
    EndSXTHItems,
    EndSXTHs,
    EndSXTupleSet,
    EndSXTupleSetData,
    EndSXTupleSetHeader,
    EndSXTupleSetRow,
    EndSxvcells,
    EndSXVD,
    EndSXVDs,
    EndSXVI,
    EndSXView,
    EndSxView14,
    EndSXView16,
    EndSXVIs,
    EndTableSlicerCache,
    EndTableStyle,
    EndTableStyles,
    EndTimelineCacheID,
    EndTimelineCacheIDs,
    EndTimelineCachePivotCacheIDs,
    EndTimelineEx,
    EndTimelinesEx,
    EndTimelineStyle,
    EndTimelineStyleElements,
    EndTimelineStyles,
    EndTimelineStylesheetExt15,
    EndUserCsView,
    EndUserCsViews,
    EndUserShView,
    EndUserShViews,
    EndVolDeps,
    EndVolMain,
    EndVolTopic,
    EndVolType,
    EndWebExtensions,
    EndWebPubItem,
    EndWebPubItems,
    EndWsSortMap,
    EndWsView,
    EndWsViews,
    EOF,
    ExternalCodeService,
    ExternalLinksAlternateUrls,
    ExternalLinksPr,
    ExternCellBlank,
    ExternCellBool,
    ExternCellError,
    ExternCellReal,
    ExternCellString,
    ExternRowHdr,
    ExternSheet,
    ExternTableEnd,
    ExternTableStart,
    ExternValueMeta,
    FieldListActiveItem,
    FileRecover,
    FileSharing,
    FileSharingIso,
    FileVersion,
    Fill,
    Filter,
    Filter14,
    FmlaBool,
    FmlaError,
    FmlaNum,
    FmlaString,
    Fmt,
    FnGroup,
    Font,
    FRTBegin,
    FRTEnd,
    HLink,
    IconFilter,
    IconFilter14,
    IndexBlock,
    IndexedColor,
    IndexPartEnd,
    IndexRowBlock,
    Info,
    ItemUniqueName,
    KnownFonts,
    LegacyDrawing,
    LegacyDrawingHF,
    List14,
    ListCCFmla,
    ListPart,
    ListTrFmla,
    Margins,
    Mdb,
    Mdtinfo,
    MdxMbrIstr,
    MergeCell,
    ModelRelationship,
    ModelTable,
    ModelTimeGroupingCalcCol,
    MRUColor,
    Name,
    NameExt,
    OleObject,
    OleSize,
    PageSetup,
    Pane,
    PCDCalcMem15,
    PCDField14,
    PCDH14,
    PCDH15,
    PCDIABoolean,
    PCDIADatetime,
    PCDIAError,
    PCDIAMissing,
    PCDIANumber,
    PCDIAString,
    PCDIBoolean,
    PCDIDatetime,
    PCDIError,
    PCDIIndex,
    PCDIMissing,
    PCDINumber,
    PCDIString,
    PCDSFCIEntry,
    PCRRecord,
    PCRRecordDt,
    PhoneticInfo,
    PivotCacheAutoRefresh,
    PivotCacheConnectionName,
    PivotCacheIdVersion,
    PivotCacheImplicitMeasureSupport,
    PivotCacheRichData,
    PivotDataFieldFutureData,
    PivotFieldFeatureSupportInfo,
    PivotFieldIgnorableAfter,
    PivotHierarchyIgnorableAfter,
    PivotLastUsedFeature,
    PivotRequiredFeature,
    PivotTableRef,
    PlaceholderName,
    PrintOptions,
    Qsi15,
    RangePr15,
    RangeProtection,
    RangeProtection14,
    RangeProtectionIso,
    RangeProtectionIso14,
    RevisionPtr,
    RichFilter,
    RichFilterDateGroupItem,
    RowHdr,
    RRAutoFmt,
    RRChgCell,
    RRConflict,
    RRDefName,
    RREndChgCell,
    RREndFormat,
    RREndInsDel,
    RREndMove,
    RRFormat,
    RRHeader,
    RRInsDel,
    RRInsertSh,
    RRMove,
    RRNote,
    RRRenSheet,
    RRSortItem,
    RRTQSIF,
    RRUserView,
    RwDescent,
    Sel,
    SheetCalcProp,
    SheetProtection,
    SheetProtectionIso,
    ShrFmla,
    Slc,
    SlicerCacheBookPivotTables,
    SlicerCacheHideItemsWithNoData,
    SlicerCacheNativeItem,
    SlicerCacheOlapItem,
    SlicerCachePivotTables,
    SlicerCacheSelection,
    SlicerStyleElement,
    SmartTagType,
    Sparkline,
    SSTItem,
    Str,
    Style,
    SupAddin,
    SupBookSrc,
    SupNameBits,
    SupNameBool,
    SupNameEnd,
    SupNameErr,
    SupNameFmla,
    SupNameNil,
    SupNameNum,
    SupNameSt,
    SupNameStart,
    SupNameValueEnd,
    SupNameValueStart,
    SupSame,
    SupSelf,
    SupTabs,
    SXDI14,
    SXDI15,
    SXDIAggregation,
    SxFilter15,
    SXTDMPOrder,
    SXTH14,
    SXTupleItems,
    SXTupleSetHeaderItem,
    SXTupleSetRowItem,
    SxvcellBool,
    SxvcellDate,
    SxvcellErr,
    SxvcellNil,
    SxvcellNum,
    SxvcellStr,
    SXVD14,
    Table,
    TableSlicerCacheID,
    TableSlicerCacheIDs,
    TableStyleClient,
    TableStyleElement,
    TextPr15,
    TimelineCachePivotCacheID,
    TimelineStyleElement,
    Top10Filter,
    Top10RichFilter,
    Uid,
    UCR,
    UserBookView,
    Usr,
    ValueMeta,
    VolBool,
    VolErr,
    VolNum,
    VolRef,
    VolStr,
    VolSubtopic,
    WbFactoid,
    WbProp,
    WbProp14,
    WebExtension,
    WebOpt,
    WorkBookPr15,
    WsDim,
    WsFmtInfo,
    WsFmtInfoEx14,
    WsProp,
    XF,
    Unsupported(u16),
}

impl RecordType {
    pub fn from_u16(record: u16) -> Self {
        match record {
            0 => RecordType::RowHdr,
            1 => RecordType::CellBlank,
            2 => RecordType::CellRk,
            3 => RecordType::CellError,
            4 => RecordType::CellBool,
            5 => RecordType::CellReal,
            6 => RecordType::CellSt,
            7 => RecordType::CellIsst,
            8 => RecordType::FmlaString,
            9 => RecordType::FmlaNum,
            10 => RecordType::FmlaBool,
            11 => RecordType::FmlaError,
            19 => RecordType::SSTItem,
            20 => RecordType::PCDIMissing,
            21 => RecordType::PCDINumber,
            22 => RecordType::PCDIBoolean,
            23 => RecordType::PCDIError,
            24 => RecordType::PCDIString,
            25 => RecordType::PCDIDatetime,
            26 => RecordType::PCDIIndex,
            27 => RecordType::PCDIAMissing,
            28 => RecordType::PCDIANumber,
            29 => RecordType::PCDIABoolean,
            30 => RecordType::PCDIAError,
            31 => RecordType::PCDIAString,
            32 => RecordType::PCDIADatetime,
            33 => RecordType::PCRRecord,
            34 => RecordType::PCRRecordDt,
            35 => RecordType::FRTBegin,
            36 => RecordType::FRTEnd,
            37 => RecordType::ACBegin,
            38 => RecordType::ACEnd,
            39 => RecordType::Name,
            40 => RecordType::IndexRowBlock,
            42 => RecordType::IndexBlock,
            43 => RecordType::Font,
            44 => RecordType::Fmt,
            45 => RecordType::Fill,
            46 => RecordType::Border,
            47 => RecordType::XF,
            48 => RecordType::Style,
            49 => RecordType::CellMeta,
            50 => RecordType::ValueMeta,
            51 => RecordType::Mdb,
            52 => RecordType::BeginFmd,
            53 => RecordType::EndFmd,
            54 => RecordType::BeginMdx,
            55 => RecordType::EndMdx,
            56 => RecordType::BeginMdxTuple,
            57 => RecordType::EndMdxTuple,
            58 => RecordType::MdxMbrIstr,
            59 => RecordType::Str,
            60 => RecordType::ColInfo,
            62 => RecordType::CellRString,
            64 => RecordType::DVal,
            65 => RecordType::SxvcellNum,
            66 => RecordType::SxvcellStr,
            67 => RecordType::SxvcellBool,
            68 => RecordType::SxvcellErr,
            69 => RecordType::SxvcellDate,
            70 => RecordType::SxvcellNil,
            128 => RecordType::FileVersion,
            129 => RecordType::BeginSheet,
            130 => RecordType::EndSheet,
            131 => RecordType::BeginBook,
            132 => RecordType::EndBook,
            133 => RecordType::BeginWsViews,
            134 => RecordType::EndWsViews,
            135 => RecordType::BeginBookViews,
            136 => RecordType::EndBookViews,
            137 => RecordType::BeginWsView,
            138 => RecordType::EndWsView,
            139 => RecordType::BeginCsViews,
            140 => RecordType::EndCsViews,
            141 => RecordType::BeginCsView,
            142 => RecordType::EndCsView,
            143 => RecordType::BeginBundleShs,
            144 => RecordType::EndBundleShs,
            145 => RecordType::BeginSheetData,
            146 => RecordType::EndSheetData,
            147 => RecordType::WsProp,
            148 => RecordType::WsDim,
            151 => RecordType::Pane,
            152 => RecordType::Sel,
            153 => RecordType::WbProp,
            154 => RecordType::WbFactoid,
            155 => RecordType::FileRecover,
            156 => RecordType::BundleSh,
            157 => RecordType::CalcProp,
            158 => RecordType::BookView,
            159 => RecordType::BeginSst,
            160 => RecordType::EndSst,
            161 => RecordType::BeginAFilter,
            162 => RecordType::EndAFilter,
            163 => RecordType::BeginFilterColumn,
            164 => RecordType::EndFilterColumn,
            165 => RecordType::BeginFilters,
            166 => RecordType::EndFilters,
            167 => RecordType::Filter,
            168 => RecordType::ColorFilter,
            169 => RecordType::IconFilter,
            170 => RecordType::Top10Filter,
            171 => RecordType::DynamicFilter,
            172 => RecordType::BeginCustomFilters,
            173 => RecordType::EndCustomFilters,
            174 => RecordType::CustomFilter,
            175 => RecordType::AFilterDateGroupItem,
            176 => RecordType::MergeCell,
            177 => RecordType::BeginMergeCells,
            178 => RecordType::EndMergeCells,
            179 => RecordType::BeginPivotCacheDef,
            180 => RecordType::EndPivotCacheDef,
            181 => RecordType::BeginPCDFields,
            182 => RecordType::EndPCDFields,
            183 => RecordType::BeginPCDField,
            184 => RecordType::EndPCDField,
            185 => RecordType::BeginPCDSource,
            186 => RecordType::EndPCDSource,
            187 => RecordType::BeginPCDSRange,
            188 => RecordType::EndPCDSRange,
            189 => RecordType::BeginPCDFAtbl,
            190 => RecordType::EndPCDFAtbl,
            191 => RecordType::BeginPCDIRun,
            192 => RecordType::EndPCDIRun,
            193 => RecordType::BeginPivotCacheRecords,
            194 => RecordType::EndPivotCacheRecords,
            195 => RecordType::BeginPCDHierarchies,
            196 => RecordType::EndPCDHierarchies,
            197 => RecordType::BeginPCDHierarchy,
            198 => RecordType::EndPCDHierarchy,
            199 => RecordType::BeginPCDHFieldsUsage,
            200 => RecordType::EndPCDHFieldsUsage,
            201 => RecordType::BeginExtConnection,
            202 => RecordType::EndExtConnection,
            203 => RecordType::BeginECDbProps,
            204 => RecordType::EndECDbProps,
            205 => RecordType::BeginECOlapProps,
            206 => RecordType::EndECOlapProps,
            207 => RecordType::BeginPCDSConsol,
            208 => RecordType::EndPCDSConsol,
            209 => RecordType::BeginPCDSCPages,
            210 => RecordType::EndPCDSCPages,
            211 => RecordType::BeginPCDSCPage,
            212 => RecordType::EndPCDSCPage,
            213 => RecordType::BeginPCDSCPItem,
            214 => RecordType::EndPCDSCPItem,
            215 => RecordType::BeginPCDSCSets,
            216 => RecordType::EndPCDSCSets,
            217 => RecordType::BeginPCDSCSet,
            218 => RecordType::EndPCDSCSet,
            219 => RecordType::BeginPCDFGroup,
            220 => RecordType::EndPCDFGroup,
            221 => RecordType::BeginPCDFGItems,
            222 => RecordType::EndPCDFGItems,
            223 => RecordType::BeginPCDFGRange,
            224 => RecordType::EndPCDFGRange,
            225 => RecordType::BeginPCDFGDiscrete,
            226 => RecordType::EndPCDFGDiscrete,
            227 => RecordType::BeginPCDSDTupleCache,
            228 => RecordType::EndPCDSDTupleCache,
            229 => RecordType::BeginPCDSDTCEntries,
            230 => RecordType::EndPCDSDTCEntries,
            231 => RecordType::BeginPCDSDTCEMembers,
            232 => RecordType::EndPCDSDTCEMembers,
            233 => RecordType::BeginPCDSDTCEMember,
            234 => RecordType::EndPCDSDTCEMember,
            235 => RecordType::BeginPCDSDTCQueries,
            236 => RecordType::EndPCDSDTCQueries,
            237 => RecordType::BeginPCDSDTCQuery,
            238 => RecordType::EndPCDSDTCQuery,
            239 => RecordType::BeginPCDSDTCSets,
            240 => RecordType::EndPCDSDTCSets,
            241 => RecordType::BeginPCDSDTCSet,
            242 => RecordType::EndPCDSDTCSet,
            243 => RecordType::BeginPCDCalcItems,
            244 => RecordType::EndPCDCalcItems,
            245 => RecordType::BeginPCDCalcItem,
            246 => RecordType::EndPCDCalcItem,
            247 => RecordType::BeginPRule,
            248 => RecordType::EndPRule,
            249 => RecordType::BeginPRFilters,
            250 => RecordType::EndPRFilters,
            251 => RecordType::BeginPRFilter,
            252 => RecordType::EndPRFilter,
            253 => RecordType::BeginPNames,
            254 => RecordType::EndPNames,
            255 => RecordType::BeginPName,
            256 => RecordType::EndPName,
            257 => RecordType::BeginPNPairs,
            258 => RecordType::EndPNPairs,
            259 => RecordType::BeginPNPair,
            260 => RecordType::EndPNPair,
            261 => RecordType::BeginECWebProps,
            262 => RecordType::EndECWebProps,
            263 => RecordType::BeginEcWpTables,
            264 => RecordType::EndECWPTables,
            265 => RecordType::BeginECParams,
            266 => RecordType::EndECParams,
            267 => RecordType::BeginECParam,
            268 => RecordType::EndECParam,
            269 => RecordType::BeginPCDKPIs,
            270 => RecordType::EndPCDKPIs,
            271 => RecordType::BeginPCDKPI,
            272 => RecordType::EndPCDKPI,
            273 => RecordType::BeginDims,
            274 => RecordType::EndDims,
            275 => RecordType::BeginDim,
            276 => RecordType::EndDim,
            277 => RecordType::IndexPartEnd,
            278 => RecordType::BeginStyleSheet,
            279 => RecordType::EndStyleSheet,
            280 => RecordType::BeginSXView,
            281 => RecordType::EndSXVI,
            282 => RecordType::BeginSXVI,
            283 => RecordType::BeginSXVIs,
            284 => RecordType::EndSXVIs,
            285 => RecordType::BeginSXVD,
            286 => RecordType::EndSXVD,
            287 => RecordType::BeginSXVDs,
            288 => RecordType::EndSXVDs,
            289 => RecordType::BeginSXPI,
            290 => RecordType::EndSXPI,
            291 => RecordType::BeginSXPIs,
            292 => RecordType::EndSXPIs,
            293 => RecordType::BeginSXDI,
            294 => RecordType::EndSXDI,
            295 => RecordType::BeginSXDIs,
            296 => RecordType::EndSXDIs,
            297 => RecordType::BeginSXLI,
            298 => RecordType::EndSXLI,
            299 => RecordType::BeginSXLIRws,
            300 => RecordType::EndSXLIRws,
            301 => RecordType::BeginSXLICols,
            302 => RecordType::EndSXLICols,
            303 => RecordType::BeginSXFormat,
            304 => RecordType::EndSXFormat,
            305 => RecordType::BeginSXFormats,
            306 => RecordType::EndSxFormats,
            307 => RecordType::BeginSxSelect,
            308 => RecordType::EndSxSelect,
            309 => RecordType::BeginISXVDRws,
            310 => RecordType::EndISXVDRws,
            311 => RecordType::BeginISXVDCols,
            312 => RecordType::EndISXVDCols,
            313 => RecordType::EndSXLocation,
            314 => RecordType::BeginSXLocation,
            315 => RecordType::EndSXView,
            316 => RecordType::BeginSXTHs,
            317 => RecordType::EndSXTHs,
            318 => RecordType::BeginSXTH,
            319 => RecordType::EndSXTH,
            320 => RecordType::BeginISXTHRws,
            321 => RecordType::EndISXTHRws,
            322 => RecordType::BeginISXTHCols,
            323 => RecordType::EndISXTHCols,
            324 => RecordType::BeginSXTDMPS,
            325 => RecordType::EndSXTDMPs,
            326 => RecordType::BeginSXTDMP,
            327 => RecordType::EndSXTDMP,
            328 => RecordType::BeginSXTHItems,
            329 => RecordType::EndSXTHItems,
            330 => RecordType::BeginSXTHItem,
            331 => RecordType::EndSXTHItem,
            332 => RecordType::BeginMetadata,
            333 => RecordType::EndMetadata,
            334 => RecordType::BeginEsmdtinfo,
            335 => RecordType::Mdtinfo,
            336 => RecordType::EndEsmdtinfo,
            337 => RecordType::BeginEsmdb,
            338 => RecordType::EndEsmdb,
            339 => RecordType::BeginEsfmd,
            340 => RecordType::EndEsfmd,
            341 => RecordType::BeginSingleCells,
            342 => RecordType::EndSingleCells,
            343 => RecordType::BeginList,
            344 => RecordType::EndList,
            345 => RecordType::BeginListCols,
            346 => RecordType::EndListCols,
            347 => RecordType::BeginListCol,
            348 => RecordType::EndListCol,
            349 => RecordType::BeginListXmlCPr,
            350 => RecordType::EndListXmlCPr,
            351 => RecordType::ListCCFmla,
            352 => RecordType::ListTrFmla,
            353 => RecordType::BeginExternals,
            354 => RecordType::EndExternals,
            355 => RecordType::SupBookSrc,
            357 => RecordType::SupSelf,
            358 => RecordType::SupSame,
            359 => RecordType::SupTabs,
            360 => RecordType::BeginSupBook,
            361 => RecordType::PlaceholderName,
            362 => RecordType::ExternSheet,
            363 => RecordType::ExternTableStart,
            364 => RecordType::ExternTableEnd,
            366 => RecordType::ExternRowHdr,
            367 => RecordType::ExternCellBlank,
            368 => RecordType::ExternCellReal,
            369 => RecordType::ExternCellBool,
            370 => RecordType::ExternCellError,
            371 => RecordType::ExternCellString,
            372 => RecordType::BeginEsmdx,
            373 => RecordType::EndEsmdx,
            374 => RecordType::BeginMdxSet,
            375 => RecordType::EndMdxSet,
            376 => RecordType::BeginMdxMbrProp,
            377 => RecordType::EndMdxMbrProp,
            378 => RecordType::BeginMdxKPI,
            379 => RecordType::EndMdxKPI,
            380 => RecordType::BeginEsstr,
            381 => RecordType::EndEsstr,
            382 => RecordType::BeginPRFItem,
            383 => RecordType::EndPRFItem,
            384 => RecordType::BeginPivotCacheIDs,
            385 => RecordType::EndPivotCacheIDs,
            386 => RecordType::BeginPivotCacheID,
            387 => RecordType::EndPivotCacheID,
            388 => RecordType::BeginISXVIs,
            389 => RecordType::EndISXVIs,
            390 => RecordType::BeginColInfos,
            391 => RecordType::EndColInfos,
            392 => RecordType::BeginRwBrk,
            393 => RecordType::EndRwBrk,
            394 => RecordType::BeginColBrk,
            395 => RecordType::EndColBrk,
            396 => RecordType::Brk,
            397 => RecordType::UserBookView,
            398 => RecordType::Info,
            399 => RecordType::CUsr,
            400 => RecordType::Usr,
            401 => RecordType::BeginUsers,
            403 => RecordType::EOF,
            404 => RecordType::UCR,
            405 => RecordType::RRInsDel,
            406 => RecordType::RREndInsDel,
            407 => RecordType::RRMove,
            408 => RecordType::RREndMove,
            409 => RecordType::RRChgCell,
            410 => RecordType::RREndChgCell,
            411 => RecordType::RRHeader,
            412 => RecordType::RRUserView,
            413 => RecordType::RRRenSheet,
            414 => RecordType::RRInsertSh,
            415 => RecordType::RRDefName,
            416 => RecordType::RRNote,
            417 => RecordType::RRConflict,
            418 => RecordType::RRTQSIF,
            419 => RecordType::RRFormat,
            420 => RecordType::RREndFormat,
            421 => RecordType::RRAutoFmt,
            422 => RecordType::BeginUserShViews,
            423 => RecordType::BeginUserShView,
            424 => RecordType::EndUserShView,
            425 => RecordType::EndUserShViews,
            426 => RecordType::ArrFmla,
            427 => RecordType::ShrFmla,
            428 => RecordType::Table,
            429 => RecordType::BeginExtConnections,
            430 => RecordType::EndExtConnections,
            431 => RecordType::BeginPCDCalcMems,
            432 => RecordType::EndPCDCalcMems,
            433 => RecordType::BeginPCDCalcMem,
            434 => RecordType::EndPCDCalcMem,
            435 => RecordType::BeginPCDHGLevels,
            436 => RecordType::EndPCDHGLevels,
            437 => RecordType::BeginPCDHGLevel,
            438 => RecordType::EndPCDHGLevel,
            439 => RecordType::BeginPCDHGLGroups,
            440 => RecordType::EndPCDHGLGroups,
            441 => RecordType::BeginPCDHGLGroup,
            442 => RecordType::EndPCDHGLGroup,
            443 => RecordType::BeginPCDHGLGMembers,
            444 => RecordType::EndPCDHGLGMembers,
            445 => RecordType::BeginPCDHGLGMember,
            446 => RecordType::EndPCDHGLGMember,
            447 => RecordType::BeginQSI,
            448 => RecordType::EndQSI,
            449 => RecordType::BeginQSIR,
            450 => RecordType::EndQSIR,
            451 => RecordType::BeginDeletedNames,
            452 => RecordType::EndDeletedNames,
            453 => RecordType::BeginDeletedName,
            454 => RecordType::EndDeletedName,
            455 => RecordType::BeginQSIFs,
            456 => RecordType::EndQSIFs,
            457 => RecordType::BeginQSIF,
            458 => RecordType::EndQSIF,
            459 => RecordType::BeginAutoSortScope,
            460 => RecordType::EndAutoSortScope,
            461 => RecordType::BeginConditionalFormatting,
            462 => RecordType::EndConditionalFormatting,
            463 => RecordType::BeginCFRule,
            464 => RecordType::EndCFRule,
            465 => RecordType::BeginIconSet,
            466 => RecordType::EndIconSet,
            467 => RecordType::BeginDatabar,
            468 => RecordType::EndDatabar,
            469 => RecordType::BeginColorScale,
            470 => RecordType::EndColorScale,
            471 => RecordType::CFVO,
            472 => RecordType::ExternValueMeta,
            473 => RecordType::BeginColorPalette,
            474 => RecordType::EndColorPalette,
            475 => RecordType::IndexedColor,
            476 => RecordType::Margins,
            477 => RecordType::PrintOptions,
            478 => RecordType::PageSetup,
            479 => RecordType::BeginHeaderFooter,
            480 => RecordType::EndHeaderFooter,
            481 => RecordType::BeginSXCrtFormat,
            482 => RecordType::EndSXCrtFormat,
            483 => RecordType::BeginSXCrtFormats,
            484 => RecordType::EndSXCrtFormats,
            485 => RecordType::WsFmtInfo,
            486 => RecordType::BeginMgs,
            487 => RecordType::EndMGs,
            488 => RecordType::BeginMGMaps,
            489 => RecordType::EndMGMaps,
            490 => RecordType::BeginMG,
            491 => RecordType::EndMG,
            492 => RecordType::BeginMap,
            493 => RecordType::EndMap,
            494 => RecordType::HLink,
            495 => RecordType::BeginDCon,
            496 => RecordType::EndDCon,
            497 => RecordType::BeginDRefs,
            498 => RecordType::EndDRefs,
            499 => RecordType::DRef,
            500 => RecordType::BeginScenMan,
            501 => RecordType::EndScenMan,
            502 => RecordType::BeginSct,
            503 => RecordType::EndSct,
            504 => RecordType::Slc,
            505 => RecordType::BeginDXFs,
            506 => RecordType::EndDXFs,
            507 => RecordType::DXF,
            508 => RecordType::BeginTableStyles,
            509 => RecordType::EndTableStyles,
            510 => RecordType::BeginTableStyle,
            511 => RecordType::EndTableStyle,
            512 => RecordType::TableStyleElement,
            513 => RecordType::TableStyleClient,
            514 => RecordType::BeginVolDeps,
            515 => RecordType::EndVolDeps,
            516 => RecordType::BeginVolType,
            517 => RecordType::EndVolType,
            518 => RecordType::BeginVolMain,
            519 => RecordType::EndVolMain,
            520 => RecordType::BeginVolTopic,
            521 => RecordType::EndVolTopic,
            522 => RecordType::VolSubtopic,
            523 => RecordType::VolRef,
            524 => RecordType::VolNum,
            525 => RecordType::VolErr,
            526 => RecordType::VolStr,
            527 => RecordType::VolBool,
            530 => RecordType::BeginSortState,
            531 => RecordType::EndSortState,
            532 => RecordType::BeginSortCond,
            533 => RecordType::EndSortCond,
            534 => RecordType::BookProtection,
            535 => RecordType::SheetProtection,
            536 => RecordType::RangeProtection,
            537 => RecordType::PhoneticInfo,
            538 => RecordType::BeginECTxtWiz,
            539 => RecordType::EndECTxtWiz,
            540 => RecordType::BeginECTWFldInfoLst,
            541 => RecordType::EndECTWFldInfoLst,
            542 => RecordType::BeginECTwFldInfo,
            548 => RecordType::FileSharing,
            549 => RecordType::OleSize,
            550 => RecordType::Drawing,
            551 => RecordType::LegacyDrawing,
            552 => RecordType::LegacyDrawingHF,
            553 => RecordType::WebOpt,
            554 => RecordType::BeginWebPubItems,
            555 => RecordType::EndWebPubItems,
            556 => RecordType::BeginWebPubItem,
            557 => RecordType::EndWebPubItem,
            558 => RecordType::BeginSXCondFmt,
            559 => RecordType::EndSXCondFmt,
            560 => RecordType::BeginSXCondFmts,
            561 => RecordType::EndSXCondFmts,
            562 => RecordType::BkHim,
            564 => RecordType::Color,
            565 => RecordType::BeginIndexedColors,
            566 => RecordType::EndIndexedColors,
            569 => RecordType::BeginMRUColors,
            570 => RecordType::EndMRUColors,
            572 => RecordType::MRUColor,
            573 => RecordType::BeginDVals,
            574 => RecordType::EndDVals,
            577 => RecordType::SupNameStart,
            578 => RecordType::SupNameValueStart,
            579 => RecordType::SupNameValueEnd,
            580 => RecordType::SupNameNum,
            581 => RecordType::SupNameErr,
            582 => RecordType::SupNameSt,
            583 => RecordType::SupNameNil,
            584 => RecordType::SupNameBool,
            585 => RecordType::SupNameFmla,
            586 => RecordType::SupNameBits,
            587 => RecordType::SupNameEnd,
            588 => RecordType::EndSupBook,
            589 => RecordType::CellSmartTagProperty,
            590 => RecordType::BeginCellSmartTag,
            591 => RecordType::EndCellSmartTag,
            592 => RecordType::BeginCellSmartTags,
            593 => RecordType::EndCellSmartTags,
            594 => RecordType::BeginSmartTags,
            595 => RecordType::EndSmartTags,
            596 => RecordType::SmartTagType,
            597 => RecordType::BeginSmartTagTypes,
            598 => RecordType::EndSmartTagTypes,
            599 => RecordType::BeginSXFilters,
            600 => RecordType::EndSXFilters,
            601 => RecordType::BeginSXFILTER,
            602 => RecordType::EndSXFilter,
            603 => RecordType::BeginFills,
            604 => RecordType::EndFills,
            605 => RecordType::BeginCellWatches,
            606 => RecordType::EndCellWatches,
            607 => RecordType::CellWatch,
            608 => RecordType::BeginCRErrs,
            609 => RecordType::EndCRErrs,
            610 => RecordType::CrashRecErr,
            611 => RecordType::BeginFonts,
            612 => RecordType::EndFonts,
            613 => RecordType::BeginBorders,
            614 => RecordType::EndBorders,
            615 => RecordType::BeginFmts,
            616 => RecordType::EndFmts,
            617 => RecordType::BeginCellXFs,
            618 => RecordType::EndCellXFs,
            619 => RecordType::BeginStyles,
            620 => RecordType::EndStyles,
            625 => RecordType::BigName,
            626 => RecordType::BeginCellStyleXFs,
            627 => RecordType::EndCellStyleXFs,
            628 => RecordType::BeginComments,
            629 => RecordType::EndComments,
            630 => RecordType::BeginCommentAuthors,
            631 => RecordType::EndCommentAuthors,
            632 => RecordType::CommentAuthor,
            633 => RecordType::BeginCommentList,
            634 => RecordType::EndCommentList,
            635 => RecordType::BeginComment,
            636 => RecordType::EndComment,
            637 => RecordType::CommentText,
            638 => RecordType::BeginOleObjects,
            639 => RecordType::OleObject,
            640 => RecordType::EndOleObjects,
            641 => RecordType::BeginSxrules,
            642 => RecordType::EndSxRules,
            643 => RecordType::BeginActiveXControls,
            644 => RecordType::ActiveX,
            645 => RecordType::EndActiveXControls,
            646 => RecordType::BeginPCDSDTCEMembersSortBy,
            648 => RecordType::BeginCellIgnoreECs,
            649 => RecordType::CellIgnoreEC,
            650 => RecordType::EndCellIgnoreECs,
            651 => RecordType::CsProp,
            652 => RecordType::CsPageSetup,
            653 => RecordType::BeginUserCsViews,
            654 => RecordType::EndUserCsViews,
            655 => RecordType::BeginUserCsView,
            656 => RecordType::EndUserCsView,
            657 => RecordType::BeginPcdSFCIEntries,
            658 => RecordType::EndPCDSFCIEntries,
            659 => RecordType::PCDSFCIEntry,
            660 => RecordType::BeginListParts,
            661 => RecordType::ListPart,
            662 => RecordType::EndListParts,
            663 => RecordType::SheetCalcProp,
            664 => RecordType::BeginFnGroup,
            665 => RecordType::FnGroup,
            666 => RecordType::EndFnGroup,
            667 => RecordType::SupAddin,
            668 => RecordType::SXTDMPOrder,
            669 => RecordType::CsProtection,
            671 => RecordType::BeginWsSortMap,
            672 => RecordType::EndWsSortMap,
            673 => RecordType::BeginRRSort,
            674 => RecordType::EndRRSort,
            675 => RecordType::RRSortItem,
            676 => RecordType::FileSharingIso,
            677 => RecordType::BookProtectionIso,
            678 => RecordType::SheetProtectionIso,
            679 => RecordType::CsProtectionIso,
            680 => RecordType::RangeProtectionIso,
            681 => RecordType::DValList,
            1024 => RecordType::RwDescent,
            1025 => RecordType::KnownFonts,
            1026 => RecordType::BeginSXTupleSet,
            1027 => RecordType::EndSXTupleSet,
            1028 => RecordType::BeginSXTupleSetHeader,
            1029 => RecordType::EndSXTupleSetHeader,
            1030 => RecordType::SXTupleSetHeaderItem,
            1031 => RecordType::BeginSXTupleSetData,
            1032 => RecordType::EndSXTupleSetData,
            1033 => RecordType::BeginSXTupleSetRow,
            1034 => RecordType::EndSXTupleSetRow,
            1035 => RecordType::SXTupleSetRowItem,
            1036 => RecordType::NameExt,
            1037 => RecordType::PCDH14,
            1038 => RecordType::BeginPCDCalcMem14,
            1039 => RecordType::EndPCDCalcMem14,
            1040 => RecordType::SXTH14,
            1041 => RecordType::BeginSparklineGroup,
            1042 => RecordType::EndSparklineGroup,
            1043 => RecordType::Sparkline,
            1044 => RecordType::SXDI14,
            1045 => RecordType::WsFmtInfoEx14,
            1046 => RecordType::BeginConditionalFormatting14,
            1047 => RecordType::EndConditionalFormatting14,
            1048 => RecordType::BeginCFRule14,
            1049 => RecordType::EndCFRule14,
            1050 => RecordType::CFVO14,
            1051 => RecordType::BeginDatabar14,
            1052 => RecordType::BeginIconSet14,
            1053 => RecordType::DVal14,
            1054 => RecordType::BeginDVals14,
            1055 => RecordType::Color14,
            1056 => RecordType::BeginSparklines,
            1057 => RecordType::EndSparklines,
            1058 => RecordType::BeginSparklineGroups,
            1059 => RecordType::EndSparklineGroups,
            1061 => RecordType::SXVD14,
            1062 => RecordType::BeginSxView14,
            1063 => RecordType::EndSxView14,
            1064 => RecordType::BeginSXView16,
            1065 => RecordType::EndSXView16,
            1066 => RecordType::BeginPCD14,
            1067 => RecordType::EndPCD14,
            1068 => RecordType::BeginExtConn14,
            1069 => RecordType::EndExtConn14,
            1070 => RecordType::BeginSlicerCacheIDs,
            1071 => RecordType::EndSlicerCacheIDs,
            1072 => RecordType::BeginSlicerCacheID,
            1073 => RecordType::EndSlicerCacheID,
            1075 => RecordType::BeginSlicerCache,
            1076 => RecordType::EndSlicerCache,
            1077 => RecordType::BeginSlicerCacheDef,
            1078 => RecordType::EndSlicerCacheDef,
            1079 => RecordType::BeginSlicersEx,
            1080 => RecordType::EndSlicersEx,
            1081 => RecordType::BeginSlicerEx,
            1082 => RecordType::EndSlicerEx,
            1083 => RecordType::BeginSlicer,
            1084 => RecordType::EndSlicer,
            1085 => RecordType::SlicerCachePivotTables,
            1086 => RecordType::BeginSlicerCacheOlapImpl,
            1087 => RecordType::EndSlicerCacheOlapImpl,
            1088 => RecordType::BeginSlicerCacheLevelsData,
            1089 => RecordType::EndSlicerCacheLevelsData,
            1090 => RecordType::BeginSlicerCacheLevelData,
            1091 => RecordType::EndSlicerCacheLevelData,
            1092 => RecordType::BeginSlicerCacheSiRanges,
            1093 => RecordType::EndSlicerCacheSiRanges,
            1094 => RecordType::BeginSlicerCacheSiRange,
            1095 => RecordType::EndSlicerCacheSiRange,
            1096 => RecordType::SlicerCacheOlapItem,
            1097 => RecordType::BeginSlicerCacheSelections,
            1098 => RecordType::SlicerCacheSelection,
            1099 => RecordType::EndSlicerCacheSelections,
            1100 => RecordType::BeginSlicerCacheNative,
            1101 => RecordType::EndSlicerCacheNative,
            1102 => RecordType::SlicerCacheNativeItem,
            1103 => RecordType::RangeProtection14,
            1104 => RecordType::RangeProtectionIso14,
            1105 => RecordType::CellIgnoreEC14,
            1111 => RecordType::List14,
            1112 => RecordType::CFIcon,
            1113 => RecordType::BeginSlicerCachesPivotCacheIDs,
            1114 => RecordType::EndSlicerCachesPivotCacheIDs,
            1115 => RecordType::BeginSlicers,
            1116 => RecordType::EndSlicers,
            1117 => RecordType::WbProp14,
            1118 => RecordType::BeginSXEdit,
            1119 => RecordType::EndSXEdit,
            1120 => RecordType::BeginSXEdits,
            1121 => RecordType::EndSXEdits,
            1122 => RecordType::BeginSXChange,
            1123 => RecordType::EndSXChange,
            1124 => RecordType::BeginSXChanges,
            1125 => RecordType::EndSXChanges,
            1126 => RecordType::SXTupleItems,
            1128 => RecordType::BeginSlicerStyle,
            1129 => RecordType::EndSlicerStyle,
            1130 => RecordType::SlicerStyleElement,
            1131 => RecordType::BeginStyleSheetExt14,
            1132 => RecordType::EndStyleSheetExt14,
            1133 => RecordType::BeginSlicerCachesPivotCacheID,
            1134 => RecordType::EndSlicerCachesPivotCacheID,
            1135 => RecordType::BeginConditionalFormattings,
            1136 => RecordType::EndConditionalFormattings,
            1137 => RecordType::BeginPCDCalcMemExt,
            1138 => RecordType::EndPCDCalcMemExt,
            1139 => RecordType::BeginPCDCalcMemsExt,
            1140 => RecordType::EndPCDCalcMemsExt,
            1141 => RecordType::PCDField14,
            1142 => RecordType::BeginSlicerStyles,
            1143 => RecordType::EndSlicerStyles,
            1144 => RecordType::BeginSlicerStyleElements,
            1145 => RecordType::EndSlicerStyleElements,
            1146 => RecordType::CFRuleExt,
            1147 => RecordType::BeginSXCondFmt14,
            1148 => RecordType::EndSXCondFmt14,
            1149 => RecordType::BeginSXCondFmts14,
            1150 => RecordType::EndSXCondFmts14,
            1152 => RecordType::BeginSortCond14,
            1153 => RecordType::EndSortCond14,
            1154 => RecordType::EndDVals14,
            1155 => RecordType::EndIconSet14,
            1156 => RecordType::EndDatabar14,
            1157 => RecordType::BeginColorScale14,
            1158 => RecordType::EndColorScale14,
            1159 => RecordType::BeginSxrules14,
            1160 => RecordType::EndSxrules14,
            1161 => RecordType::BeginPRule14,
            1162 => RecordType::EndPRule14,
            1163 => RecordType::BeginPRFilters14,
            1164 => RecordType::EndPRFilters14,
            1165 => RecordType::BeginPRFilter14,
            1166 => RecordType::EndPRFilter14,
            1167 => RecordType::BeginPRFItem14,
            1168 => RecordType::EndPRFItem14,
            1169 => RecordType::BeginCellIgnoreECs14,
            1170 => RecordType::EndCellIgnoreECs14,
            1171 => RecordType::DXF14,
            1172 => RecordType::BeginDxF14s,
            1173 => RecordType::EndDxf14s,
            1177 => RecordType::Filter14,
            1178 => RecordType::BeginCustomFilters14,
            1180 => RecordType::CustomFilter14,
            1181 => RecordType::IconFilter14,
            1182 => RecordType::PivotCacheConnectionName,
            2048 => RecordType::BeginDecoupledPivotCacheIDs,
            2049 => RecordType::EndDecoupledPivotCacheIDs,
            2050 => RecordType::DecoupledPivotCacheID,
            2051 => RecordType::BeginPivotTableRefs,
            2052 => RecordType::EndPivotTableRefs,
            2053 => RecordType::PivotTableRef,
            2054 => RecordType::SlicerCacheBookPivotTables,
            2055 => RecordType::BeginSxvcells,
            2056 => RecordType::EndSxvcells,
            2057 => RecordType::BeginSxRow,
            2058 => RecordType::EndSxRow,
            2060 => RecordType::PCDCalcMem15,
            2067 => RecordType::Qsi15,
            2068 => RecordType::BeginWebExtensions,
            2069 => RecordType::EndWebExtensions,
            2070 => RecordType::WebExtension,
            2071 => RecordType::AbsPath15,
            2072 => RecordType::BeginPivotTableUISettings,
            2073 => RecordType::EndPivotTableUISettings,
            2075 => RecordType::TableSlicerCacheIDs,
            2076 => RecordType::TableSlicerCacheID,
            2077 => RecordType::BeginTableSlicerCache,
            2078 => RecordType::EndTableSlicerCache,
            2079 => RecordType::SxFilter15,
            2080 => RecordType::BeginTimelineCachePivotCacheIDs,
            2081 => RecordType::EndTimelineCachePivotCacheIDs,
            2082 => RecordType::TimelineCachePivotCacheID,
            2083 => RecordType::BeginTimelineCacheIDs,
            2084 => RecordType::EndTimelineCacheIDs,
            2085 => RecordType::BeginTimelineCacheID,
            2086 => RecordType::EndTimelineCacheID,
            2087 => RecordType::BeginTimelinesEx,
            2088 => RecordType::EndTimelinesEx,
            2089 => RecordType::BeginTimelineEx,
            2090 => RecordType::EndTimelineEx,
            2091 => RecordType::WorkBookPr15,
            2092 => RecordType::PCDH15,
            2093 => RecordType::BeginTimelineStyle,
            2094 => RecordType::EndTimelineStyle,
            2095 => RecordType::TimelineStyleElement,
            2096 => RecordType::BeginTimelineStylesheetExt15,
            2097 => RecordType::EndTimelineStylesheetExt15,
            2098 => RecordType::BeginTimelineStyles,
            2099 => RecordType::EndTimelineStyles,
            2100 => RecordType::BeginTimelineStyleElements,
            2101 => RecordType::EndTimelineStyleElements,
            2102 => RecordType::DXF15,
            2103 => RecordType::BeginDXFs15,
            2104 => RecordType::EndDXFs15,
            2105 => RecordType::SlicerCacheHideItemsWithNoData,
            2106 => RecordType::BeginItemUniqueNames,
            2107 => RecordType::EndItemUniqueNames,
            2108 => RecordType::ItemUniqueName,
            2109 => RecordType::BeginExtConn15,
            2110 => RecordType::EndExtConn15,
            2111 => RecordType::BeginOledbPr15,
            2112 => RecordType::EndOledbPr15,
            2113 => RecordType::BeginDataFeedPr15,
            2114 => RecordType::EndDataFeedPr15,
            2115 => RecordType::TextPr15,
            2116 => RecordType::RangePr15,
            2117 => RecordType::DbCommand15,
            2118 => RecordType::BeginDbTables15,
            2119 => RecordType::EndDbTables15,
            2120 => RecordType::DbTable15,
            2121 => RecordType::BeginDataModel,
            2122 => RecordType::EndDataModel,
            2123 => RecordType::BeginModelTables,
            2124 => RecordType::EndModelTables,
            2125 => RecordType::ModelTable,
            2126 => RecordType::BeginModelRelationships,
            2127 => RecordType::EndModelRelationships,
            2128 => RecordType::ModelRelationship,
            2129 => RecordType::BeginECTxtWiz15,
            2130 => RecordType::EndECTxtWiz15,
            2131 => RecordType::BeginECTWFldInfoLst15,
            2132 => RecordType::EndECTWFldInfoLst15,
            2133 => RecordType::BeginECTwFldInfo15,
            2134 => RecordType::FieldListActiveItem,
            2135 => RecordType::PivotCacheIdVersion,
            2136 => RecordType::SXDI15,
            2137 => RecordType::BeginModelTimeGroupings,
            2138 => RecordType::EndModelTimeGroupings,
            2139 => RecordType::BeginModelTimeGrouping,
            2140 => RecordType::EndModelTimeGrouping,
            2141 => RecordType::ModelTimeGroupingCalcCol,
            3072 => RecordType::Uid,
            3073 => RecordType::RevisionPtr,
            4096 => RecordType::BeginDynamicArrayPr,
            4097 => RecordType::EndDynamicArrayPr,
            5002 => RecordType::BeginRichValueBlock,
            5003 => RecordType::EndRichValueBlock,
            5081 => RecordType::BeginRichFilters,
            5082 => RecordType::EndRichFilters,
            5083 => RecordType::RichFilter,
            5084 => RecordType::BeginRichFilterColumn,
            5085 => RecordType::EndRichFilterColumn,
            5086 => RecordType::BeginCustomRichFilters,
            5087 => RecordType::EndCustomRichFilters,
            5088 => RecordType::CustomRichFilter,
            5089 => RecordType::Top10RichFilter,
            5090 => RecordType::DynamicRichFilter,
            5092 => RecordType::BeginRichSortCondition,
            5093 => RecordType::EndRichSortCondition,
            5094 => RecordType::RichFilterDateGroupItem,
            5095 => RecordType::BeginCalcFeatures,
            5096 => RecordType::EndCalcFeatures,
            5097 => RecordType::CalcFeature,
            5099 => RecordType::ExternalLinksPr,
            5100 => RecordType::PivotCacheImplicitMeasureSupport,
            5101 => RecordType::PivotFieldIgnorableAfter,
            5102 => RecordType::PivotHierarchyIgnorableAfter,
            5103 => RecordType::PivotDataFieldFutureData,
            5105 => RecordType::PivotCacheRichData,
            5108 => RecordType::ExternalLinksAlternateUrls,
            5109 => RecordType::BeginPivotVersionInfo,
            5110 => RecordType::EndPivotVersionInfo,
            5111 => RecordType::BeginCacheVersionInfo,
            5112 => RecordType::EndCacheVersionInfo,
            5113 => RecordType::PivotRequiredFeature,
            5114 => RecordType::PivotLastUsedFeature,
            5117 => RecordType::ExternalCodeService,
            5130 => RecordType::SXDIAggregation,
            5131 => RecordType::PivotFieldFeatureSupportInfo,
            5132 => RecordType::PivotCacheAutoRefresh,

            other => RecordType::Unsupported(other),
        }
    }
}
