[package]
name = "wasmql"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
rules = { path = "../rules" }
pgrules = { path = "../pgrules" }
pest = { workspace = true }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
getrandom = { version = "0.2", features = ["js"] }