[package]
name = "pgrules"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }

[dependencies]
rules = { path = "../rules" }
pest = { workspace = true }
postgres-protocol = "0.6.6"
tracing = { workspace = true }
time = { workspace = true, features=["parsing"] }
sha2 = "0.10.8"
hex = "0.4.3"
semver = { workspace = true }
humantime = "2.1.0"
postgres-types = { version = "0.2", optional = true }
bytes = { version = "1.10", optional = true }

[features]
interval = ["dep:postgres-types", "dep:bytes"]