[package]
name = "from_record_derive"
version = "0.1.0"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0.81"
