[package]
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true
name = "grapher"
description = "Job result to graphdb converter"

[dependencies]
shared = { path = "../shared" }
tokio = { workspace = true, features = ["signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
amqprs = { workspace = true }
figment = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
tokio-postgres = { workspace = true }
async-trait = { workspace = true }
