[package]
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true
name = "sigmgr"
description = "ClamAV signatures manager"

[dependencies]
shared = { path = "../shared" }
tokio = { workspace = true, features = ["process", "signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
amqprs = { workspace = true }
figment = { workspace = true }
tokio-postgres = { workspace = true }
pgrules = { workspace = true }
rand = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
