[package]
name = "rules-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.pgrules]
path = "../pgrules"

[[bin]]
name = "pgrules"
path = "fuzz_targets/pgrules.rs"
test = false
doc = false
bench = false